language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install

script:
  - npm run build

deploy:
  - provider: script
    script: "cp .npmrc.template $HOME/.npmrc && npm run build-bundle && npm publish"
    skip_cleanup: true
    on:
      tags: true

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    target-branch: gh-pages
    local-dir: dist
    on:
      branch: master
